### PR TITLE
Updated Cross Remote to v2.0

### PR DESCRIPTION
**Pull request by leedave**
# Application Submission

- Now has the Ability to also send SubGhz Signals 
- Fixed Memory Leaks
- Fix bug causing crash after deleting item
- Change to file format to support individual IR timings in future

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by leedave** [comment]
I'm totally confused? Why isn't the catalog accepting the use of **lib/subghz/protocols/protocol_items.h**?
The official SubGhz App uses this, also it has absolutely no issue compiling locally with fbt. 

@doomwastaken can you give me a hint on how to solve this?

**Comment by doomwastaken** [comment]
@leedave on it, will message in a bit

**Comment by doomwastaken** [comment]
@leedave as far as I was able to figure out, that file is not included into our SDK, which means you need to define SDK headers in your .fam file

Here is an example from one of the apps
`App(
    appid="cli",
    name="CliSrv",
    apptype=FlipperAppType.SERVICE,
    entry_point="cli_srv",
    cdefines=["SRV_CLI"],
    stack_size=4 * 1024,
    order=30,
    sdk_headers=["cli.h", "cli_vcp.h"],
)
`

**Comment by doomwastaken** [comment]
Additionally you cannot use firmware icons, you will need to copy them and use them separately. Those are 2 errors that I get when I try to build your app separately. 

Also I assume your app folder is somewhere inside your firmware folder, because that is only way I was able to build it with ./fbt

**Comment by leedave** [comment]
@doomwastaken 
Unfortunately I'm still stuck

I figured out, that my custom keyboard was using FW icon even though I already had them in the apps icon folder. That one is fixed. However the hint with **sdk_headers** is still confusing me. I've been trying different variants without success

```
sdk_headers=["<lib/subghz/protocols/protocol_items.h>"],
```

```
sdk_headers=["lib/subghz/protocols/protocol_items.h"],
```

```
sdk_headers=["protocol_items.h"],
```

None of these additions to the **application.fam** have any affect. uFBT refuses to recognize the include. I don't understand why, as it is a standard include from the original firmware, like so many others in custom apps and it works flawlessly when compiliing in the firmwares **applications_user** folder. To me it seems like a bug in uFBT, but you can probably judge that better. 

Also comparing the application.fam of the official subghz app I see no entry for sdk_headers, even tho it uses exactly the same include. 

Could you give me another hint?

**Comment by leedave** [comment]
I figured it out 👍 

I noticed the library is unfortunately missing in I replaced the api_symbols.csv. I don't quite understand why, as it seems very important to me, but I solved the issue in uFBT by 
replacing
```
#include <lib/subghz/protocols/protocol_items.h>
```

with a similar include that is in api_symbols.csv
```
#include <lib/subghz/subghz_protocol_registry.h>
```

Now uFBT build it. I also tested some basic transmissions and my app seems happy with the change. 
New PR was sent

**Pull request closed without merging**
