### PR TITLE
Updated Flipper Authenticator to v4.0.1

### PR DESCRIPTION
**Pull request by akopachov**
# Application Submission

Updated Flipper Authenticator to [v4.0.1](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v4.0.1)

# Extra Requirements 

No

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Review by hedger — CHANGES_REQUESTED** [review]
scons: *** [/home/runner/.ufbt/build/totp/lib/wolfssl/wolfcrypt/src/pwdbased.o] Error 1
cc1: fatal error: app/wolfssl_config.h: No such file or directory

**Comment by hedger** [comment]
You can set additional flags for a fap's library with `cdefines`, and add paths to its include path with `cincludes`. See [description of fields](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/AppManifests.md#parameters-for-external-applications) for `fap_private_libs`.

**Comment by akopachov** [comment]
Need your help to understand the cause. As the mentioned file obviously [is in place](https://github.com/akopachov/flipper-zero_authenticator/blob/a02382f1d23384f20be3ef45b70cc97d9eb44388/totp/wolfssl_config.h). 

Does uFBT correctly sets `${FAP_SRC_DIR}` variable when processing `.fam` file?

Normal FBT builds with no issue.

**Comment by hedger** [comment]
Yes, ${FAP_SRC_DIR} is being set to a virtual path in context of uFBT. That's a bug. 
I'll see it can be worked around.

**Comment by hedger** [comment]
FAP_SRC_DIR should be fixed by https://github.com/flipperdevices/flipperzero-firmware/pull/2970

However, 
1. it also comes with changes to crypto API we discussed some time ago, so your app must be updated 
2. good news - same PR also adds application's root dir to its include paths, so instead of 
```C
#include "../../types/common.h"
#include "../../types/crypto_settings.h"
```
now you can write
```C
#include <types/common.h>
#include <types/crypto_settings.h>
```
3. please fix `cflags=["-Wno-error", "-include${FAP_SRC_DIR}/wolfssl_config.h"]` by moving config files to a separate dir (for example, `config/features.h`, `config/wolfssl/config.h`), adding `cdefines=["HAVE_CONFIG_H"],` and adding `cincludes=["config/wolfssl"],` for that lib.

**Comment by akopachov** [comment]
Thanks for the update. Working on app updates

**Comment by akopachov** [comment]
Updated. Should be good to go

**Review by hedger — APPROVED** [review]
Nice - waiting for firmware's RC to merge this. 
RC is coming in the next 1-2 days.

**Comment by hedger** [comment]
NVM - I see you implemented workarounds for supporting various API versions. Cool. 
Merging

**Review by hedger — APPROVED** [review]

**Pull request merged**
