### PR TITLE
Flipperscope manifest

### PR DESCRIPTION
**Pull request by anfractuosity**
# Application Submission

Simple oscilloscope type application that graphs analogue voltages
and calculate min/max voltages along with the frequency of the signal.

# Extra Requirements 

Simply attach a signal generator etc. to pin C0 of the flipper zero

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I validated my manifest [to be valid](../blob/HEAD/documentation/Contributing.md#validating-manifest)

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Review by hedger — CHANGES_REQUESTED** [review]
Nice app!
Can you add wiring requirements to app description and/or in-app info screen, please?

**Review by hedger — APPROVED** [review]
<snip>

**Review by hedger — CHANGES_REQUESTED** [review]
see previous comment

**Comment by anfractuosity** [comment]
Thanks, I've just modified my app so it has a description on the pins to use in the about section
and in fap_description.  The hash is - e1c593e8b63c92d8954be3f0c669b5fa6975293a would you be able to add that to 
the manifest for me?

**Review by hedger — APPROVED** [review]

**Pull request merged**
