### PR TITLE
Upgrade to v2.0

### PR DESCRIPTION
**Pull request by QtRoS**
Just pushed my v2.0 version to master-branch, trying to update the app in store

# Application Submission

- Massive internal refactoring and new app structure
- "Scroll to ..." menu item which allows you to scroll to any percent of the file

# Extra Requirements 

- [ Describe if your application requires any extra hardware or software ]

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Review by hedger — CHANGES_REQUESTED** [review]
Please run validation scripts locally before submitting the update.

**Comment by QtRoS** [comment]
@hedger I tried to validate, but after calling this command
image
It gives:
```bash
...
RecursionError: maximum recursion depth exceeded
```
Dunno how to fix :( BTW I'm doing it on Windows.

Anyway, just by looking at the build error:
image
I want to say it doesn't look like my app's error. More likely that something is wrong with the toolchain.

**Comment by hedger** [comment]
You seem to have an ancient verison of ufbt installed. Please remove it, including its location in PATH.
Then re-run validation script.

**Comment by QtRoS** [comment]
> You seem to have an ancient verison of ufbt installed

I used [this](https://github.com/flipperdevices/flipper-application-catalog/blob/HEAD/documentation/Contributing.md#validating-manifest) instruction to setup environment yesterday. 

But luckily the error [changed](https://github.com/flipperdevices/flipper-application-catalog/actions/runs/6771020771/job/18410159286?pr=176) to this:
image

More meaningful, will try to investigate and fix

**Comment by QtRoS** [comment]
Previous `commit_sha` was: e1326198ec587571e2ec87b0da042b9ada571a42
I thought the hash should be from my repo, but now I understood that I should pick the last one from here: https://github.com/xMasterX/all-the-plugins/commits/dev/base_pack/hex_viewer

But I can't see recent changes from my repo which I [commited yesterday](https://github.com/QtRoS/flipper-zero-hex-viewer/commits/master). Should I wait?

**Comment by hedger** [comment]
If you're changing app's source code repo to your own, you should reflect that in the manifest file. I updated it for you.

Now, please fix build errors. Apps built by ufbt cannot use firmware's image assets and must bring images they need to their own repo.

**Comment by QtRoS** [comment]
@hedger I hope I [did it](https://github.com/QtRoS/flipper-zero-hex-viewer/commit/b982fa50a3c677e6a414aa9807187fc0d408d56c) right.

**Comment by hedger** [comment]
Not yet.
https://github.com/QtRoS/flipper-zero-hex-viewer/pull/4

**Comment by QtRoS** [comment]
Merged, updated hash, now waiting for the rebuild

**Comment by doomwastaken** [comment]
`Error: 09:10:59.702 [E] Icon hex_10px.png is not black and white`

**Comment by QtRoS** [comment]
@doomwastaken fixed, now icon is in BMP format

**Comment by doomwastaken** [comment]
19:02:28.591 [E] Path not found: /tmp/tmpzfnzkwp4/code/img/2.png
@QtRoS now there is a missing screenshot

**Comment by QtRoS** [comment]
Added screenshots to `img` folder, changed hash. Hope this try is final

**Comment by doomwastaken** [comment]
Error: 20:38:30.299 [E] Short description is empty

Check example manifest in the docs, it also requires short description for catalog apps

**Comment by QtRoS** [comment]
Fixed it too. Local build with `ufbt` also works fine. Hope everything is ok now

image

**Review by doomwastaken — APPROVED** [review]
All good

**Comment by doomwastaken** [comment]
Yeah! All works, merging it!

**Pull request merged**
