### PR TITLE
Fix broken description

### PR DESCRIPTION
**Pull request by Matt-London**
# Application Submission

- Fixed broken description from last submission

# Extra Requirements 

- No new requirements

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by doomwastaken** [comment]
@Matt-London this was bad, should have checked the bundle along the fap.

**Comment by doomwastaken** [comment]
Sadly there is a limited markdown support, check the docs or other PRs for details. Backtick is not supported. 

Usual workaround is either simplifying readme file or having a separate one just for the catalog description. Limitations are due to limited markdown support on mobile companions

**Comment by Matt-London** [comment]
@doomwastaken Somehow I had an old commit hash though I tested bundling with the correct one. The correct hash is now pushed

**Comment by doomwastaken** [comment]
Edited my first comment xD forgot the "my" part xD

**Review by doomwastaken — APPROVED** [review]

**Comment by Matt-London** [comment]
@doomwastaken All good, thanks for the merge!

**Pull request merged**
