### PR TITLE
Bump IR Intervalometer Version to 0.2.2

### PR DESCRIPTION
**Pull request by Nitepone**
Fixes compile issues

# Application Submission

- Fixes callback signature changed in new Flipper SDK version

# Extra Requirements 

- None

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by doomwastaken** [comment]
you need to bump version, version 1.2 already exists

**Comment by Nitepone** [comment]
Version number updated. Increased to 2.2 to better match versions from my own repo.

**Comment by doomwastaken** [comment]
https://github.com/Nitepone/flipper-intervalometer/blob/1c7699859c6f94345db70c3771759e1b8226ce42/application.fam
version is still 1.2, that is the bump I was talking about

**Comment by Nitepone** [comment]
Ah, sigh, sorry that's my bad. Fixed now!

**Review by doomwastaken — APPROVED** [review]

**Pull request merged**
