### PR TITLE
Add XRemote IR app

### PR DESCRIPTION
**Pull request by kala13x**
# Application Submission

Advanced IR Remote App for Flipper Zero Device

# Extra Requirements 

No extra software or hardware required.

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s)

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by doomwastaken** [comment]
@kala13x I am crashing when I try to enter saved. Maybe there is no check whether key folder actually exists?

**Comment by doomwastaken** [comment]
Also pressing learn->back->learn crashes the app too

**Comment by kala13x** [comment]
@doomwastaken Can you please share .fap file? Because I just tried both scenarios and not crashing with me. 
I've used the latest firmware from the master branch to build the app and ran it on the flipper with firmware 0.92.2 (installed with qflipper)

**Review by doomwastaken — CHANGES_REQUESTED** [review]
Two comments in the conversation. If you would like to proceed with update regardless, then just message us

**Comment by doomwastaken** [comment]
[flipper_xremote-1.0-build-artifacts.zip](https://github.com/flipperdevices/flipper-application-catalog/files/12844929/flipper_xremote-1.0-build-artifacts.zip)
or you can see them in builds details -> summary

**Comment by kala13x** [comment]
@doomwastaken What firmware version do you have on Flipper? Because it not crashing with me even with these artifacts. I tried to completely remove infrared folder from SD card but not crashing anyway.

**Comment by doomwastaken** [comment]
Oh, I was on test branch, let me check on release

**Comment by doomwastaken** [comment]
It is my bad, all works fine on release and my flippers sadly are only NFC refactor branch recently. Verified, all works

**Review by doomwastaken — APPROVED** [review]

**Pull request merged**
