### PR TITLE
Seader: Bump to 1.2

### PR DESCRIPTION
**Pull request by bettse**
# Application Submission

- Bumping to fix random naming include change

# Extra Requirements 

- Requires uart to sam interface ("nard")

# Author Checklist (Fill this out)

- [X] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [X] I own the code I'm submitting or have code owner's permission to submit it
- [X] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s)

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by doomwastaken** [comment]
Found a crash

Nothing connected to flipper, go to load, go back, exit app, null pointer

Otherwise all good

**Comment by bettse** [comment]
> Nothing connected to flipper, go to load, go back, exit app, null pointer

Can you give me more explicit instructions?  I'm trying to reproduce and it isn't.  After starting the app, does it detect the sam?  if so, I assume you're on the main manu, do you select "Load" from the menu next?  If you hit back from this screen it will do the SAM detection again, so are you letting it do that, or hitting back while it is attempting?  What screen are you on just before you exit the app?

**Comment by doomwastaken** [comment]
Yeah, tried it again. Correct way to reproduce is either click retry or load and quickly click back twice, that will force flipper to freeze.

**Comment by bettse** [comment]
I haven’t had time to repro, but I can imagine how this could Halle .  That said, I think it predates even v1.0, so I’d like to get this PR merged to fix the random name generation change, and attend to that as a bug.

**Review by doomwastaken — APPROVED** [review]

**Comment by doomwastaken** [comment]
No worries, was just letting you know!

**Pull request merged**
