### PR TITLE
Add '[ESP32] Camera Suite' application.

### PR DESCRIPTION
**Pull request by CodyTolene**
# Application Submission

Adds v1.1.0 of the ESP32-CAM software "[ESP32] Camera Suite" (https://github.com/CodyTolene/Flipper-Zero-Camera-Suite). This software has multiple views for settings, guiding the user, and for displaying the camera. The camera has multiple in-use options using various keys on the Flipper Zero, and the camera can be rotated to fit your module placement.

# Extra Requirements 

- An ESP32-CAM module is needed. Hardware setup and installation guide [here](https://github.com/CodyTolene/Flipper-Zero-Camera-Suite#hardware-installation).
- Custom firmware is needed on the ESP32-CAM module. See [here](https://github.com/CodyTolene/Flipper-Zero-Camera-Suite#firmware-installation) for more details.

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I validated my manifest [to be valid](../blob/HEAD/documentation/Contributing.md#validating-manifest)

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Review by hedger — CHANGES_REQUESTED** [review]
Please fix errors from the build log

**Comment by CodyTolene** [comment]
I believe this is now ready again. Thanks @hedger

**Comment by CodyTolene** [comment]
I believe this is now ready again. Thanks @hedger

**Review by hedger — CHANGES_REQUESTED** [review]
Still some issues remaining:
- please put app version in application.fam, not .yml
- certain markdown features are not supported. 

Please run bundler script, as explained in the docs, to verify your submission.

**Comment by CodyTolene** [comment]
I'm new to Python, but I managed to get the virtual environment up along with the dependencies. 

In the final step of [your instructions](https://github.com/flipperdevices/flipper-application-catalog/blob/HEAD/documentation/Contributing.md#validating-manifest) I'm having an issue running the script
 `python3 tools/bundle.py applications/.../manifest.yml bundle.zip`
image

If I try with `py` (`py tools/bundle.py applications/.../manifest.yml bundle.zip`) I get the following
image

Using Windows 11 Pro. I will keep at it and trying to figure this out. It's probably a configuration issue.

**Comment by hedger** [comment]
@CodyTolene 
You're supposed to pass path to your newly created manifest.yml in place of `applications/...`.

**Comment by CodyTolene** [comment]
>You're supposed to pass path to your newly created manifest.yml in place of applications/....

@hedger 

Thank you! To fix the issue on Windows I also had to run `ufbt` first which installed items needed via Windows toolchain.
```batch
py -m pip install --upgrade ufbt
ufbt cli
```
I'm now able to run the build and I see now what I need to fix up locally. I've updated this PR to be a draft until I get the items worked out. Thanks again, updates coming soon...

**Comment by CodyTolene** [comment]
Ready!
image

Thanks @hedger

**Review by hedger — APPROVED** [review]

**Review by hedger — APPROVED** [review]

**Pull request merged**
