### PR TITLE
Add Apple BLE Spam

### PR DESCRIPTION
**Pull request by noproto**
# Application Submission

- This application spams broadcast packets to Apple devices, which may be up to 5 meters away. It was ported to OFW and backported to previous releases.

# Extra Requirements 

- None

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s)

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by skotopes** [comment]
@noproto in continuation of our Saturday talk: we can not accept app in this form.

But we can accept general purpose app that satisfies following conditions:
- Not called `Apple BLE Spam`
- Performs BLE adv according to user provided file
- Files with adv content are not shipped with app

**Comment by Hacklesshub** [comment]
How do I download?

**Comment by kilianbalaguer** [comment]
v

**Review by lucasammy — COMMENTED** [review]
🙏🙏🙏

**Comment by kilianbalaguer** [comment]
jfldf

**Pull request closed without merging**
