### PR TITLE
Updated Authenticator to v3.1.0

### PR DESCRIPTION
**Pull request by akopachov**
# Application Submission

- Updated Authenticator to [v3.1.0](https://github.com/akopachov/flipper-zero_authenticator/releases/tag/v3.1.0)

# Extra Requirements 

- No

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I validated my manifest [to be valid](../blob/HEAD/documentation/Contributing.md#validating-manifest)

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by hedger** [comment]
We can accept this update, however, you had wrong information on keys storage. First 10 keys are all the same between all Flippers.

**Comment by hedger** [comment]
We will come back with details on keys management in the near future.

**Comment by akopachov** [comment]
Hm, okay, so could you please confirm if information provided [here](https://github.com/flipperdevices/flipperzero-firmware/issues/2885#issuecomment-1646664666) is correct or not? If not I'm going to revoke this release and create another one disallowing usage of key indexes < 10

**Comment by akopachov** [comment]
nvm. I just updated code do disallow first 11 key slots. Should be ready for review

**Comment by hedger** [comment]
Which keys will it use then, if there are no keys on device besides factory-provided?

**Comment by hedger** [comment]
We will contact you on the keys management topic today - after going through your current implementation.

**Comment by akopachov** [comment]
Before using key slot app checks it using [`totp_crypto_check_key_slot`](https://github.com/akopachov/flipper-zero_authenticator/blob/bd5c79cdecad24a69d50516195b1a54e0988ecc5/totp/services/crypto/crypto_facade.c#L7C27-L7C27) function which is using `furi_hal_crypto_verify_key`. If I understood `furi_hal_crypto_verify_key` function correctly, it checks if key is available and can be used and if it is not, then it generates new unique key for a given slot.

**Comment by hedger** [comment]
See this comment: https://github.com/flipperdevices/flipperzero-firmware/issues/2885#issuecomment-1652148724

**Comment by akopachov** [comment]
Converting to "draft" for now to take a look at [this](https://github.com/akopachov/flipper-zero_authenticator/issues/172) showstopper

**Comment by akopachov** [comment]
Showstopper fixed. Should be ready for review.

**Comment by akopachov** [comment]
Is there anything else what is blocking this app revision to go live?

**Review by hedger — APPROVED** [review]

**Review by hedger — APPROVED** [review]
Merging - but API will break in the next release.

**Comment by hedger** [comment]
Additional request: could you please migrate authenticator data catalog from /ext/authenticator to /ext/apps_data/... to comply with data storage recommendations, macro `APP_DATA_PATH`?

**Comment by akopachov** [comment]
> Additional request: could you please migrate authenticator data catalog from /ext/authenticator to /ext/apps_data/... to comply with data storage recommendations, macro `APP_DATA_PATH`?

Are you guys going to do the same migration for u2f app?
image

**Comment by hedger** [comment]
@akopachov, thanks for pointing that out. U2F will be updated to EXT_PATH(), it is useless without an SD card (and won't even run without one ATM). However, being a part of main menu apps and one of core applications, it is not subject to the common external app requirements.

p.s. - check out `storage_common_migrate` helper

**Pull request merged**
