### PR TITLE
Sync good faps with main repo

### PR DESCRIPTION
**Pull request by skotopes**
# Application Submission

- Sync good faps with main repo

# Extra Requirements 

- Tests

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s)

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by skotopes** [comment]
@bettse picopass included, please let us know if it shouldn't.

**Comment by bettse** [comment]
it is good to be included 👍

**Comment by skotopes** [comment]
Nice, then waiting for @doomwastaken to merge this PR

**Comment by doomwastaken** [comment]
@nminaylov there is a small text overflow issue in mass storage, just name your drive with bunch of W letters

**Review by doomwastaken — APPROVED** [review]

**Pull request merged**
