### PR TITLE
Update "Camera Suite" application to v1.4.1

### PR DESCRIPTION
**Pull request by CodyTolene**
# Application Submission

- Update "[ESP32] Camera Suite" application fap from v1.4.0 to v1.4.1 (patch).
- Removes use of an image that no longer exists in the new firmware.

# Extra Requirements 

- Firmware is required for the ESP32-CAM module, see readme [here](https://github.com/CodyTolene/Flipper-Zero-Camera-Suite).

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

### CODE REVIEW

**Review by hedger — CHANGES_REQUESTED** [review]
Internally, FAPs store only major.minor version components. And they are used to check if app version is already known to the backend. Since there already is a 1.4 on the backend, please change version to 1.5.

**Comment by CodyTolene** [comment]
Will do. Thanks @hedger !

**Comment by CodyTolene** [comment]
Will do. Thanks @hedger !

**Comment by CodyTolene** [comment]
Fixed up here: https://github.com/flipperdevices/flipper-application-catalog/pull/252

**Pull request closed without merging**
