### PR TITLE
Web crawler v0.2

### PR DESCRIPTION
**Pull request by jblanked**
# Application Submission

- Changed serial functions from synchronous to asynchronous.
- Added error handling for GET requests and WiFi Dev Board connections.
- Updated the WiFi Dev Board firmware (FlipperHTTP) to trigger three quick green LED blinks when the board is first connected, a solid green LED when the board receives a serial command, and a solid green LED while the board is processing.
- Added auto-connect and auto-disconnect for WiFi when a user enters or leaves the app.
- Added an option to see the saved data

# Extra Requirements 

- WiFi Devboard for Flipper Zero with WebCrawler Flash: https://github.com/jblanked/WebCrawler-FlipperZero/tree/main/assets/FlipperHTTP
- Wifi Access Point

# Author Checklist (Fill this out)

- [X] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [X] I own the code I'm submitting or have code owner's permission to submit it
- [X] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

### CODE REVIEW

**Review by hedger — DISMISSED** [review]
Please resolve merge conflicts.

**Comment by jblanked** [comment]
I thought the conflict was the new manfiest.yml. Is there something that I missed?

**Comment by jblanked** [comment]
My apolgoies. Let me know if that fixed it.

**Comment by hedger** [comment]
All good now, thanks.

**Comment by jblanked** [comment]
Awesome, is there anything else I need to do on my end?

**Review by doomwastaken — APPROVED** [review]

**Pull request merged**
