### PR TITLE
Armixz/programmercalc 0.9

### PR DESCRIPTION
**Pull request by armixz**
# Application Submission

- Programmer Calculator - Initial release v0.9
- This version marks its initial release, bringing various number system conversions crucial for embedded systems development, debugging, and digital electronics design.

- Features
  - Decimal to Binary conversion
  - Decimal to Hexadecimal conversion
  - Decimal to Character display
  - Hexadecimal to Binary conversion
  - Hexadecimal to Decimal conversion
  - Binary to Decimal conversion
  - Binary to Hexadecimal conversion

# Extra Requirements 

- No extra hardware is required to run this application on Flipper Zero devices.

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Review by hedger — CHANGES_REQUESTED** [review]
All screnshots must be horizontal (not rotated).

**Comment by armixz** [comment]
Thank you @hedger

- Manifest file has been validated
  - `HEAD is now at 843bd1d resize screenshot`
  - `02:26:02.802 [I] Checked out commit 843bd1ddac863b7b5c2689600ae66da34267dace. Updating submodules`
  - `02:26:04.122 [I] Moving C:\Users\armin\AppData\Local\Temp\tmpegik2d4t to C:\Users\XXX\AppData\Local\Temp\tmpg7diexyo\code`
  - `02:26:04.125 [I] Building`
  - `02:26:10.263 [I] Value for 'name' is empty in YAML. Using value 'Programmer Calculator' from FAM.`
  - `02:26:10.264 [I] Value for 'id' is empty in YAML. Using value 'programmercalc' from FAM.`
  - `02:26:10.265 [I] Value for 'category' is empty in YAML. Using value 'Tools' from FAM.`
  - `02:26:10.266 [I] Value for 'icon' is empty in YAML. Using value 'calcIcon.png' from FAM.`
  - `02:26:10.266 [I] Value for 'short_description' is empty in YAML. Using value 'Calculator, for Programmers!' from FAM.`
  - `02:26:10.267 [I] Value for 'targets' is empty in YAML. Using value '['all']' from FAM.`
  - `02:26:10.267 [I] Value for 'version' is empty in YAML. Using value '0.9' from FAM.`
  - `02:26:10.418 [E] Screenshot C:\Users\armin\AppData\Local\Temp\tmpg7diexyo\code\img\1.png has resolution 128x64, downscaled to 1x1, expected 128x64`
- The screenshot has been downscaled and rotated under [commit](https://github.com/armixz/Flipper-Zero-Programmer-Calculator/commit/843bd1ddac863b7b5c2689600ae66da34267dace), but I am still getting an error regarding screenshot resolution. I don't understand what the issue is.
  - `[E] Screenshot C:\Users\XXX\AppData\Local\Temp\tmpg7diexyo\code\img\1.png has resolution 128x64, downscaled to 1x1, expected 128x64`

**Comment by hedger** [comment]
OK - I think the issue is that bundler script is not flexible enough to support downsized and rotated images. Could you please just rotate the image produced by qFlipper so its dimensions are `512 × 256`?

We'll improve the bundler script later, so it could support rotated imaged produced by qFlipper.

**Comment by armixz** [comment]
@hedger 
Can I update the manifest to version 0.9.2 of the app, or should I submit a new pull request? 
The version was 0.9 when I initially submitted the app.

What's new:
- Enhanced output quality
- Increased buffer size
- Enhanced error handling

**Review by doomwastaken — APPROVED** [review]

**Pull request merged**
