### PR TITLE
dlvoy/game vexed 1.0.1

### PR DESCRIPTION
**Pull request by dlvoy**
# Application Submission

Vexed game - remake of Palm.OS Vexed for Flipper Zero

# Extra Requirements 

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by dlvoy** [comment]
I just found crash on clean install (empty SD) when game is continued after restart - related to empty extra levels, will publish fix soon, sorry!

**Comment by dlvoy** [comment]
Fixed!

**Comment by doomwastaken** [comment]
Cool intro

**Review by doomwastaken — APPROVED** [review]

**Comment by dlvoy** [comment]
Thanks for reviewing and merging!

**Pull request merged**
