### PR TITLE
Added Authenticator v5.16.1

### PR DESCRIPTION
**Pull request by akopachov**
# Application Submission

- Software-based authenticator that implements multi-factor authentication services using the time-based one-time password (TOTP; specified in [RFC 6238](https://www.rfc-editor.org/rfc/rfc6238)) and HMAC-based One-time Password algorithm (HOTP; specified in [RFC 4226](https://www.rfc-editor.org/rfc/rfc4226)), for authenticating users of software applications.

# Extra Requirements 

- There is a companion app for desktop allowing you to interact with Flipper Authenticator in a more user-friendly way. The latest builds as well as all the information about it can be found in its official repo [here](https://github.com/akopachov/flipper-zero_authenticator-companion)

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by akopachov** [comment]
From what I uderstand, `fal_embedded` should be set to `True` in manifest to let build system pack all `.fal` files into `fap`. So I did that [here](https://github.com/akopachov/flipper-zero_authenticator/blob/master_ofw-catalog/totp/application.fam).

Unfortunately build fails:

```text
fbt: warning: Failed parsing manifest 'tmpz8bo1uux\code\application.fam' : App totp cannot have fal_embedded set
```

if I set `fal_embedded` to `False` or remove, build passes, but from what I understand, your delivery system will not be able to deliver all the `fal` files alongside with `fap`.

**Comment by hedger** [comment]
> From what I uderstand, `fal_embedded` should be set to `True` in manifest to let build system pack all `.fal` files into `fap`. So I did that [here](https://github.com/akopachov/flipper-zero_authenticator/blob/master_ofw-catalog/totp/application.fam).

That's right. But `fal_embedded` is a property for plugins' manifests only, not the host application. Set it to true for every plugin and it should work.

**Comment by akopachov** [comment]
Ah, yeah, my bad.
Fixed.
Thanks

**Comment by akopachov** [comment]
**As a note for QA**: it would be great if you make sure that at least `totp version` CLI command is working just fine, to make sure that all the `fal` files are in place

**Review by doomwastaken — APPROVED** [review]

**Comment by doomwastaken** [comment]
Greetings! Sorry for delay, I am currently on vacation and struggling with internet connection (or lack of!). I will ask one of my colleagues to test, since I have no way of downloading the app. As far as I can tell .fal did include correctly, but I did not check all plugins. 

Usually we do minimal check for the .fap itself, basically that it runs and do minimal tests to it (depending on complexity, code and type of an app). 

But I can tell, this is an extremely useful app and a great addition. Thank you for contribution

**Comment by doomwastaken** [comment]
Great work and sorry for delay!

**Pull request merged**
