### PR TITLE
Update Color Guess for 0.95.0-rc

### PR DESCRIPTION
**Pull request by leedave**
# Application Submission

- Color Guessing Game, updated for 0.95.0-rc

# Extra Requirements 

- None

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Review by doomwastaken — CHANGES_REQUESTED** [review]
Looks like icon is not black and white. Also app will need version bump if you haven't done yet. 

Will update all other comments to users, since I might have missed some info in original message. Thank you

**Comment by leedave** [comment]
@doomwastaken 
I have a version bump ready. But I'm struggling with the Icon issue. It's setup the same way as other app icons that worked. Is there any way to figure out what is not good with the image?

**Comment by doomwastaken** [comment]
Checked out your repo and it is odd that it doesn't work. Seems black and white to me, will get back to you in a bit

**Comment by doomwastaken** [comment]
You seem to have double converted the image, I see several shades in your PNG

Here is an example, it needs to be only 0x000000 0xFFFFFF
image

**Comment by leedave** [comment]
@doomwastaken 
Thank you for the great support. I fixed up the icon.

**Review by doomwastaken — APPROVED** [review]
All great! Thank you

**Pull request merged**
