### PR TITLE
Add Malveke Apps manifest

### PR DESCRIPTION
**Pull request by EstebanFuentealba**
# Application Submission

- **[MALVEKE] GAME BOY Cartridge (GB/GBC)**: Interacts with GAME BOY and GAME BOY Color cartridges. You can Dump & Restore RAM and ROM.
- **[MALVEKE] GAME BOY ADVANCE Cartridge**: Interacts with GAME BOY ADVANCE cartridges. You can read Information.
- **[MALVEKE] GAME BOY Link-Camera**: MALVEKE app, this application allows you to extract your GAME BOY Camera pictures via WIFI for easy sharing with your phone, tablet, or PC. It's user-friendly; simply connect it to your GAME BOY and print as usual. The device will store the images and share them on a web server via WIFI. You will need a printer cable or GAME BOY Color link cable for this.
- **[MALVEKE] GB Live Camera**: Inserting a GAME BOY Camera cartridge, you can use it as a camera and take snapshots from the Flipper Zero.
- **[MALVEKE] Pokemon Trading**: Pokemon exchange from Flipper Zero to Game Boy for Generation I (Pokemon Red, Blue, Yellow)

# Extra Requirements 

- [MALVEKE PCB](https://www.tindie.com/products/efuentealba/malveke-game-boy-tools-for-flipper-zero/)
- GAME BOY Color / Advance
- Cable Link

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

### CODE REVIEW

**Review by doomwastaken — CHANGES_REQUESTED** [review]
Markdown element 'Short_reference' is not allowed
All other apps are fine

**Comment by EstebanFuentealba** [comment]
> FYI: now you can also submit multiple applications in a single PR.
Thank you, what a relief, hahaha.

**Comment by doomwastaken** [comment]
@hedger 
image
having issues with app icons. Was checking cartridge app, commit leads to latest commit in repo, downloaded PNG and it only has one correct color 0xFFFFFF
@EstebanFuentealba consider that [MALVEKE] takes half of a string, hard to distinguish apps between themselves

**Review by doomwastaken — CHANGES_REQUESTED** [review]
@EstebanFuentealba you cannot have transparent layer in icon. Has to be 0x000000 (white) color. This will fix app icons

**Review by doomwastaken — APPROVED** [review]

**Pull request merged**
