### PR TITLE
Fix Knit Counter description

### PR DESCRIPTION
**Pull request by fridgepoet**
# Application Submission

Sorry, the description formatting was a little unexpected, so I have tried to fix it here.
Thanks for reviewing my submission so quickly!

# Extra Requirements 

- None

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by doomwastaken** [comment]
> Sorry, fixing that now.

don't worry about that, I don't think it is correct behavior on our side. Imagine that you want to update description and all users have to update their app because of that, has to be 2 entities, one app and another one manifest. Will discuss this with team

**Review by doomwastaken — APPROVED** [review]

**Comment by doomwastaken** [comment]
on bright side, counter persists through an app update

**Comment by fridgepoet** [comment]
Is there any way the description can be previewed, by the way? I didn't expect the short description from the .fam to be concatenated with the verbose description of the manifest.

**Comment by doomwastaken** [comment]
@fridgepoet 
image
I hope this is helpful. Might not be 100% up to date with layout. We will update it and submit to the docs

**Comment by fridgepoet** [comment]
Thanks @doomwastaken, however I think it is missing one part that I didn't expect. I am not sure exactly when it takes the "short description," but the "short description" also appears in the Description section at the top. I've marked it with the red box in your image below. That's the part I didn't expect.

It's no longer the case for my app, but here's another app where the short description is above the detailed description if you check their App Page: https://github.com/flipperdevices/flipper-application-catalog/blob/main/applications/RFID/key_generator/manifest.yml


288052175-cea683b6-faed-4c3b-bc8d-5c0e6c4cb542

**Pull request merged**
