### PR TITLE
Update Unitemp to 1.4

### PR DESCRIPTION
**Pull request by quen0n**
# Application Submission

- Small fixes

# Extra Requirements 

- none

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by quen0n** [comment]
ok, fix it later. ufbt successfully build the application on my computer

**Comment by doomwastaken** [comment]
You cannot use system icons in the apps, you will need to add file to assets and use it that way.

**Comment by quen0n** [comment]
Done

**Comment by quen0n** [comment]
image
Now it's definitely ready without errors or warnings

**Review by doomwastaken — APPROVED** [review]

**Comment by quen0n** [comment]
Thank you

**Pull request merged**
