### PR TITLE
Tester for fiscal drive

### PR DESCRIPTION
**Pull request by polarikus**
# Application Submission
Application for testing the fiscal drive (Only for the Russian market): https://kontur.ru/ofd/spravka/401-chto_takoe_fn 
The fiscal drive is connected to the flipper via the UART interface. Connection information is in the Wiring menu of the application

# Extra Requirements 

- None

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s)

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Review by hedger — CHANGES_REQUESTED** [review]
Can you please change app version from 0.0? It might cause issues with the backend.

**Comment by polarikus** [comment]
> Can you please change app version from 0.0? It might cause issues with the backend.

Done

**Comment by hedger** [comment]
> Done

Awesome, thanks! One more request - could you please also translate the description to English? I totally understand that the app is targeting Russian audience, but everything in the public catalog's UI is in English so all users can understand what the app is designed for.

https://www.deepl.com/ru/translator can save your time :)

**Comment by polarikus** [comment]
> translate the description to English

Ok! Done :)

**Review by hedger — APPROVED** [review]

**Pull request merged**
