### PR TITLE
FlipStore - v0.1

### PR DESCRIPTION
**Pull request by jblanked**
# Application Submission

- Download Flipper Zero apps directly to your Flipper Zero using WiFi. 

# Extra Requirements 

- WiFi Dev Board for Flipper Zero with FlipperHTTP Flash: https://github.com/jblanked/WebCrawler-FlipperZero/tree/main/assets/FlipperHTTP
- WiFi Access Point

# Author Checklist (Fill this out)

- [X] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [X] I own the code I'm submitting or have code owner's permission to submit it
- [X] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by jblanked** [comment]
#530 referencing these questions from: https://github.com/flipperdevices/flipper-application-catalog/pull/530#discussion_r1807433696

It is using https://catalog.flipperzero.one/api/v0/0/application?limit=500&is_latest_release_version=true&offset=0&sort_by=updated_at&sort_order=-1 to get the list of available apps, then it parses a simpler JSON format to send back to the Flipper.

For downloading apps, it sends a request to https://catalog.flipperzero.one/api/v0/application/version/{app_data["current_version"]["_id"]}/bundle to download the bundle.zip. Then it uses UFBT to compile the code located in the code folder. Then afterwards, it sends back the bytes of the .fap file to the Flipper

It's using version the latest version always (well I assume those links will produce the latest versions each time). 

It does currently save the apps to a custom folder within the apps called "FlipStore". I did my development on Unleashed and based off your comment, I'm assuming custom folders cannot be created in the apps directory? If that's the case, I'll need to integrate the different app categories much much sooner than I planned.

Thank you again for taking the time to review the apps and provide feedback. I do plan on open-sourcing flipsocial.net and am more than happy to share/explain any code.

**Comment by skotopes** [comment]
I see. 

Let me start with small excurse: from the beginning of the catalog development we realized it is going to be quite difficult child. Nature of the platform doesn't allow us to maintain stable API and we were forced to design it around idea that everything changes and often in major way. So we've made system that continuously builds apps against constantly changing set of SDKs and archives artifacts in a way that we can deliver apps to as many different firmware as possible. That plus installation manifests became catalog we know now. Taking in account all the complexity and in order to keep behavior among the companions consistent we intentionally left API private. 

And that brings us to the present moment: in order for us to accept this PR you must implement everything that we did in companions. Otherwise you'll bring mess into their flow.

In general we can accept that and provide additional resources if needed.
But that's going to be quite difficult journey.

Also I think that if we going to pull it off then we'll have to update wifi board firmware to provide seamless socket/web API on the system level, so no custom wifi board firmware will be needed. To be honest we've been thinking about it for a while and it is in our task backlog.

PS: list of things that companion apps implements:
- app group query based on firmware API version
- app query based on firmware API version and group
- app installation based on firmware API version and installation manifest creation
- app update based on firmware API version and version from installation manifest
- installation manifests(Flipper File Format) load, verify, maintain 
- various deployment related stuff: creating directory folders, consistent deployment of app and manifest at the same time and etc...

**Comment by jblanked** [comment]
Thank you for providing such a detailed breakdown of the creation and maintenance of the API and SDK.

I agree that this is a challenging journey, and honestly, downloading apps was just the tip of the iceberg. By version 1.0, I aimed to facilitate downloading and updating system firmware.

If I'm permitted to proceed, I would greatly appreciate any help you can provide with this project, as well as any resources you could share. I hope that the [FlipperHTTP flash](https://github.com/jblanked/WebCrawler-FlipperZero/tree/main/assets/FlipperHTTP) is at least a step forward.

I'm open to making any changes or additions as needed.

I had a thought: if the API is maintained by your team, couldn't FlipStore continue to use it? Or, even simpler, just use UFBT to compile .faps from GitHub repositories?

Thanks again for your help, and I look forward to hopefully collaborating.

**Comment by jblanked** [comment]
My apologies, I didn't mean to close/delete the branch. I was doing some clean up.

**Comment by jblanked** [comment]
I just bumped the version to 0.2:

- Refactored the code using the Easy Flipper library.
- Added categories: Users can now navigate through categories, and when FlipStore installs a selected app, it will download directly to the corresponding category's folder in the apps directory.
- Improved memory allocation to prevent "Out of Memory" warnings.
- Updated installation messages.

I also changed the endpoints for installing .fap files. Now, it directly uses the following URL: https://catalog.flipperzero.one/api/v0/application/version/%s/build/compatible?target=%s&api=%s.

I look forward to your response and would like to thank you and your team again for your guidance and support.

**Comment by noproto** [comment]
In addition to what has been written on this issue, SSL/TLS verification by the HTTP library should never be used in [bypass mode](https://github.com/jblanked/FlipperHTTP/blob/main/Arduino/FlipperHTTP.h#L411) or users may be targeted by MITM attacks when installing apps (however unlikely - consider events like DEFCON).

**Comment by jblanked** [comment]
> [bypass mode](https://github.com/jblanked/FlipperHTTP/blob/main/Arduino/FlipperHTTP.h#L411)

Understood, thanks for your input. If I remember correctly, I'd need to provide a certificate to use the client securely. I'll look into this and come up with a solution. Any feedback or suggestions is appreciated.

**Pull request closed without merging**
