### PR TITLE
FastJS v1.0

### PR DESCRIPTION
**Pull request by jblanked**
# Application Submission

- FastJS allows users to pre-save their selected JavaScript files for quick execution. Since users can't currently set scripts to Favorite App or Dummy Mode buttons, they can favorite FastJS instead. In the configuration view, users can choose which script to save and opt for FastJS to remember their selection. Utilizing the storage library, FastJS securely saves user preferences for seamless access. Thank you for taking the time to review this app!

# Extra Requirements 

- N/A

# Author Checklist (Fill this out)

- [X] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [X] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by doomwastaken** [comment]
Also you can add scripts to favorites by navigating to file browsers (Down -> Left) and then going to Apps->Scripts and selecting Pin on the desired script. That does not help with dummy mode and quick selects though

**Comment by doomwastaken** [comment]
[E] Path not found: /tmp/tmp5117ak33/code/gallery/02-about.png

Most likely you have files locally and forgot to commit them, that is why build fails on our side

**Comment by jblanked** [comment]
I see, there was a typo in that file name. Re-compiling now. Thanks again

**Comment by jblanked** [comment]
Everything should compile now. I'm sorry for any confusion.
Screenshot 2024-09-25 at 7 03 25 AM

**Review by doomwastaken — APPROVED** [review]

**Pull request merged**
