### PR TITLE
Added Flipper SPI terminal v0.1

### PR DESCRIPTION
**Pull request by janwiesemann**
# Application Submission

- It's an application for communicating with other devices over SPI.

# Extra Requirements 

- None

# Author Checklist (Fill this out)

- [X] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [X] I own the code I'm submitting or have code owner's permission to submit it
- [X] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [x] Bundle is valid
- [x] There are no obvious issues with the source code
- [x] I've ran this application and verified its functionality

### CODE REVIEW

**Comment by doomwastaken** [comment]
Greetings!` /code/CHANGELOG.md` path is not found

**Comment by doomwastaken** [comment]
Now I am curious whether it is possible that its case sensitive

**Comment by janwiesemann** [comment]
@doomwastaken Interesting...

I've used the `tool/bundle.py` script to validate my manifest beforehand. It hasn't raised any errors or warnings.

```
janwiesemann@Jans-MacBook-Pro flipper-application-catalog % python3.12 tools/bundle.py --nolint applications/GPIO/flipper_spi_terminal/manifest.yml bundle.zip 
10:27:37.698 [I] Deploying SDK for f7
10:27:37.698 [I] Fetching version info for UpdateChannel.RELEASE from https://update.flipperzero.one/firmware/directory.json
10:27:38.177 [I] Using version: 1.1.2
10:27:38.177 [I] uFBT SDK dir: /Users/janwiesemann/.ufbt/current
10:27:38.178 [I] SDK is up-to-date
10:27:38.261 [I] Working in '/private/var/folders/mj/qp601k_s0rx3cwsv6chm7_6h0000gn/T/tmpxnrkain4'
10:27:38.262 [I] Loaded app manifest from applications/GPIO/flipper_spi_terminal/manifest.yml
10:27:38.262 [I] Cloning https://github.com/janwiesemann/flipper-spi-terminal.git to /private/var/folders/mj/qp601k_s0rx3cwsv6chm7_6h0000gn/T/tmp9nqrqtfz
Cloning into '/private/var/folders/mj/qp601k_s0rx3cwsv6chm7_6h0000gn/T/tmp9nqrqtfz'...
remote: Enumerating objects: 281, done.
remote: Counting objects: 100% (281/281), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 281 (delta 178), reused 217 (delta 114), pack-reused 0 (from 0)
Receiving objects: 100% (281/281), 124.20 KiB | 2.96 MiB/s, done.
Resolving deltas: 100% (178/178), done.
10:27:39.031 [I] Cloned. Checking out commit 3599d268d0f8ba3b51389f665d44ac8174ce8347
HEAD is now at 3599d26 Added README_app_catalog.MD for Flipper App catalog
10:27:39.048 [I] Checked out. Updating submodules
10:27:39.115 [I] Moving /private/var/folders/mj/qp601k_s0rx3cwsv6chm7_6h0000gn/T/tmp9nqrqtfz to /private/var/folders/mj/qp601k_s0rx3cwsv6chm7_6h0000gn/T/tmpxnrkain4/code
10:27:39.115 [I] Building
10:27:40.372 [I] Value for 'name' is empty in YAML. Using value 'SPI-Terminal' from FAM.
10:27:40.372 [I] Value for 'id' is empty in YAML. Using value 'flipper_spi_terminal' from FAM.
10:27:40.372 [I] Value for 'author' is empty in YAML. Using value 'Jan Wiesemann' from FAM.
10:27:40.372 [I] Value for 'category' is empty in YAML. Using value 'GPIO' from FAM.
10:27:40.372 [I] Value for 'icon' is empty in YAML. Using value 'flipper_spi_terminal_10px.png' from FAM.
10:27:40.372 [I] Value for 'short_description' is empty in YAML. Using value 'A Terminal Application for the SPI interface' from FAM.
10:27:40.373 [I] Value for 'targets' is empty in YAML. Using value '['all']' from FAM.
10:27:40.373 [I] Value for 'version' is empty in YAML. Using value '0.1' from FAM.
10:27:40.373 [I] Including changelog from file /private/var/folders/mj/qp601k_s0rx3cwsv6chm7_6h0000gn/T/tmpxnrkain4/code/CHANGELOG.md
10:27:40.373 [I] Including description from file /private/var/folders/mj/qp601k_s0rx3cwsv6chm7_6h0000gn/T/tmpxnrkain4/code/README_app_catalog.MD
10:27:40.409 [I] Saving updated manifest with skip_source_code=False
10:27:40.423 [I] Bundle created: bundle.zip
```

I've adjusted the casing. to match the repo.

**Comment by doomwastaken** [comment]
Odd that it is case sensitive, I will ask why it was made this way, might be just an oversight. Either way, now it builds, I will check it and merge shortly

**Review by doomwastaken — APPROVED** [review]

**Pull request merged**
